---
- name: Verify
  hosts: all
  tasks:
    - name: Check if frontproxy directory exists
      stat:
        path: /opt/frontproxy
      register: frontproxy_dir

    - name: Ensure frontproxy directory exists
      assert:
        that:
          - frontproxy_dir.stat.exists
    
    - name: Check if docker-compose file is deployed
      stat:
        path: /opt/frontproxy/docker-compose.yml
      register: compose_file

    - name: Ensure docker-compose file is deployed
      assert:
        that:
          - compose_file.stat.exists

    - name: Check if Dockerfile is deployed
      stat:
        path: /opt/frontproxy/nginx/Dockerfile
      register: dockerfile
      
    - name: Ensure Dockerfile is deployed
      assert:
        that:
          - dockerfile.stat.exists
